# Generated by Django 5.1.15 on 2026-04-02 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ADD_TO_CART', 'Add to Cart'), ('BEGIN_CHECKOUT', 'Begin Checkout'), ('PURCHASE', 'Purchase'), ('NEWSLETTER_SIGNUP', 'Newsletter Signup')], max_length=25)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'analytics_conversion_event',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_c_event_t_b4c179_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'analytics_page_view',
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_44ef74_idx')],
            },
        ),
    ]
