# Generated by Django 5.1.15 on 2026-04-02 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_stock_level',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase / Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage / Loss')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive=in, negative=out')),
                ('reference', models.CharField(blank=True, help_text='Order ID, PO number, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stocklevel')),
            ],
            options={
                'db_table': 'inventory_movement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock_level', 'movement_type'], name='inventory_m_stock_l_57ee0d_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_m_movemen_15f5ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('order_reference', models.CharField(blank=True, max_length=255)),
                ('stock_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.stocklevel')),
            ],
            options={
                'db_table': 'inventory_stock_reservation',
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='inventory_s_is_acti_016d2a_idx')],
            },
        ),
    ]
