# Generated by Django 5.1.15 on 2026-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['email', 'created_at'], name='accounts_ot_email_f4b9fa_idx'),
        ),
    ]
