# Generated by Django 5.1.15 on 2026-04-02 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'search queries',
                'db_table': 'search_query',
            },
        ),
    ]
