# Generated by Django 5.1.15 on 2026-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesession',
            name='checkout_url',
            field=models.TextField(blank=True),
        ),
    ]
